[env:esp32s3_camera]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Monitor speed
monitor_speed = 115200

; --- SETUP MEMORY ---
; Flash 16MB
board_upload.flash_size = 16MB
board_build.flash_mode = qio

; setup PSRAM
board_build.arduino.memory_type = qio_opi 

; build flags
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue